services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/wifi_points
    volumes:
      - .:/app

  db:
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wifi_points
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d wifi_points"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: